CREATE TABLE IF NOT EXISTS transactions(
    transaction_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    account_id BIGINT NOT NULL,
    operationtype_id SMALLINT NOT NULL,
    amount DECIMAL(10,2) NOT NULL,
    event_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);